services:
  potniq:
    build: ./docker/bun
    container_name: Potniq

    volumes:
      - ./src:/usr/src/app

    environment:
      - NODE_ENV=development

  example:
    build: ./docker/node
    container_name: Example
    platform: linux/x86_64

    volumes:
      - ./example:/app
      - ./src/:/app/potniq

    ports:
      - 3000:3000

    environment:
      - NODE_ENV=development