services:
  node:
    build: ./docker/node
    container_name: Node

    volumes:
      - ./src:/app

    environment:
      - NODE_ENV=development

  example:
    build: ./docker/node
    container_name: Example

    volumes:
      - ./example:/app

    environment:
      - NODE_ENV=development